insert into professions (name) values ('Paralegal');
insert into professions (name) values ('Staff Accountant IV');
insert into professions (name) values ('Sales Associate');
insert into professions (name) values ('Administrative Officer');
insert into professions (name) values ('Tax Accountant');
insert into professions (name) values ('Structural Engineer');
insert into professions (name) values ('Cost Accountant');
insert into professions (name) values ('Structural Analysis Engineer');
insert into professions (name) values ('Administrative Officer');
insert into professions (name) values ('Assistant Manager');
insert into professions (name) values ('Accountant IV');
insert into professions (name) values ('Information Systems Manager');
insert into professions (name) values ('Programmer IV');
insert into professions (name) values ('Design Engineer');
insert into professions (name) values ('Web Developer II');
insert into professions (name) values ('VP Accounting');
insert into professions (name) values ('Research Assistant II');
insert into professions (name) values ('Senior Developer');
insert into professions (name) values ('VP Product Management');
insert into professions (name) values ('Staff Accountant II');
insert into professions (name) values ('VP Product Management');
insert into professions (name) values ('Web Designer III');
insert into professions (name) values ('Electrical Engineer');
insert into professions (name) values ('Administrative Assistant III');
insert into professions (name) values ('Food Chemist');
insert into professions (name) values ('Mechanical Systems Engineer');
insert into professions (name) values ('Marketing Manager');
insert into professions (name) values ('Speech Pathologist');
insert into professions (name) values ('VP Marketing');
insert into professions (name) values ('Tax Accountant');